services:
  postgres:
    image: "postgres:16.2-alpine"
    restart: always
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - net-container