services:
  auth-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: auth-server
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: always
