spring.application.name=auth
server.port=${APP_PORT:8080}
# Jwt
security.jwt.secret-key=${JWT_SECRET:c2VuaGEgZXh0cmVtYW1lbnRlIHBvdGVudGUgcGFyYSBwb2RlciBjcmlwdG9ncmFmYXI=}
security.jwt.refresh-expiration-time=${REFRESH_EXPIRATION:604800000}
security.jwt.expiration-time=${JWT_EXPIRATION:900000}
# Database
spring.data.mongodb.uri=${DB_URI:mongodb://admin:admin123.@localhost:27017/auth?authSource=admin}
spring.data.mongodb.database=${DB_NAME:auth}
# Admin
admin.name=${NAME_ADMIN:admin}
admin.email=${EMAIL_ADMIN:admin@auth.com}
admin.password=${PASSWORD_ADMIN:admin123}
# Exception Handling
spring.web.resources.add-mappings=false
spring.mvc.throw-exception-if-no-handler-found=true
server.error.whitelabel.enabled=false
server.error.include-stacktrace=never
# SpringDoc / Swagger
security.jwt.cookie.secure=${JWT_COOKIE_SECURE:false}
springdoc.show-hateoas-endpoints=false
# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%X{requestId}] [%X{userEmail}] [%X{clientIp}] --- [%t] %-40.40logger{39} : %m%n
